name: Deploy to Deployment Repo

on:
  push:
    branches:
      - main  # 자동 배포를 트리거할 브랜치를 지정합니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"

      - name: Push to deployment repository
        run: |
          git remote add deploy https://github.com/jifrozen0110/front_deploy.git
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.DEPLOY_REPO_TOKEN }} | base64)"
          git push deploy HEAD:main --force
